In [9]:
# #From chatGPT 
# #
# import pandas as pd
# import csv

# def clean_hmda_csv(file_path):
#     # Open the csv file in read mode and create a reader object
#     with open(file_path, 'r') as csv_file:
#         reader = csv.reader(csv_file)
        
#         # Get the header row
#         header = next(reader)
        
#         # Create a list to store the cleaned data
#         cleaned_data = []
        
#         # Loop over the remaining rows in the file
#         for row in reader:
#             # Skip the row if it has less than 50000 columns
#             if len(row) < 50000:
#                 continue
                
#             # Clean each column in the row
#             cleaned_row = [clean_column(col) for col in row]
            
#             # Add the cleaned row to the cleaned_data list
#             cleaned_data.append(cleaned_row)
            
#     # Write the cleaned data to a new csv file
#     with open('cleaned_hmda.csv', 'w', newline='') as csv_file:
#         writer = csv.writer(csv_file)
        
#         # Write the header row
#         writer.writerow(header)
        
#         # Write the cleaned data
#         writer.writerows(cleaned_data)
        
# def clean_column(col):
#     # Code to clean the data in the column
#     # For example:
#     # Remove leading and trailing whitespaces
#     return col.strip()

# hmda_clean = clean_hmda_csv('./input_data/state_AZ-CA_mini.csv')
# hmda_clean.type()
# #hmda_cleanDF = pd.read_csv(hmda_clean)
# #hmda_clean.to_csv('./data/hmdaclean.csv')

import pandas as pd

def clean_hmda_csv(file_path):
    # Load the csv file into a pandas DataFrame
    df = pd.read_csv(file_path)
    
    # Remove leading and trailing whitespaces from each column
    df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
    
    return df

hmdadf = clean_hmda_csv('./input_data/state_AZ-CA_mini.csv')
hmdadf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 99 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   activity_year                             50000 non-null  int64
 1   lei                                       50000 non-null  object
 2   derived_msa-md                            50000 non-null  int64
 3   state_code                                50000 non-null  object
 4   county_code                               49821 non-null  float64
 5   census_tract                              49783 non-null  float64
 6   conforming_loan_limit                     49809 non-null  object
 7   derived_loan_product_type                 50000 non-null  object
 8   derived_dwelling_category                 50000 non-null  object
 9   derived_ethnicity                         50000 non-null  object
 10  derived_race                              50000 non-null  object
 11  derived_sex                               50000 non-null  object
 12  action_taken                              50000 non-null  int64
 13  purchaser_type                            50000 non-null  int64
 14  preapproval                               50000 non-null  int64
 15  loan_type                                 50000 non-null  int64
 16  loan_purpose                              50000 non-null  int64
 17  lien_status                               50000 non-null  int64
 18  reverse_mortgage                          50000 non-null  int64
 19  open-end_line_of_credit                   50000 non-null  int64
 20  business_or_commercial_purpose            50000 non-null  int64
 21  loan_amount                               50000 non-null  float64
 22  loan_to_value_ratio                       33134 non-null  object
 23  interest_rate                             35693 non-null  object
 24  rate_spread                               28021 non-null  object
 25  hoepa_status                              50000 non-null  int64
 26  total_loan_costs                          30300 non-null  object
 27  total_points_and_fees                     377 non-null    object
 28  origination_charges                       30655 non-null  object
 29  discount_points                           11852 non-null  object
 30  lender_credits                            13485 non-null  object
 31  loan_term                                 49396 non-null  object
 32  prepayment_penalty_term                   1313 non-null   object
 33  intro_rate_period                         4486 non-null   object
 34  negative_amortization                     50000 non-null  int64
 35  interest_only_payment                     50000 non-null  int64
 36  balloon_payment                           50000 non-null  int64
 37  other_nonamortizing_features              50000 non-null  int64
 38  property_value                            39142 non-null  object
 39  construction_method                       50000 non-null  int64
 40  occupancy_type                            50000 non-null  int64
 41  manufactured_home_secured_property_type   50000 non-null  int64
 42  manufactured_home_land_property_interest  50000 non-null  int64
 43  total_units                               50000 non-null  object
 44  multifamily_affordable_units              303 non-null    object
 45  income                                    43219 non-null  float64
 46  debt_to_income_ratio                      32464 non-null  object
 47  applicant_credit_score_type               50000 non-null  int64
 48  co-applicant_credit_score_type            50000 non-null  int64
 49  applicant_ethnicity-1                     49980 non-null  float64
 50  applicant_ethnicity-2                     4356 non-null   float64
 51  applicant_ethnicity-3                     58 non-null     float64
 52  applicant_ethnicity-4                     1 non-null      float64
 53  applicant_ethnicity-5                     0 non-null      float64
 54  co-applicant_ethnicity-1                  49993 non-null  float64
 55  co-applicant_ethnicity-2                  1832 non-null   float64
 56  co-applicant_ethnicity-3                  16 non-null     float64
 57  co-applicant_ethnicity-4                  0 non-null      float64
 58  co-applicant_ethnicity-5                  0 non-null      float64
 59  applicant_ethnicity_observed              50000 non-null  int64
 60  co-applicant_ethnicity_observed           50000 non-null  int64
 61  applicant_race-1                          49985 non-null  float64
 62  applicant_race-2                          4731 non-null   float64
 63  applicant_race-3                          414 non-null    float64
 64  applicant_race-4                          36 non-null     float64
 65  applicant_race-5                          13 non-null     float64
 66  co-applicant_race-1                       49997 non-null  float64
 67  co-applicant_race-2                       2133 non-null   float64
 68  co-applicant_race-3                       179 non-null    float64
 69  co-applicant_race-4                       13 non-null     float64
 70  co-applicant_race-5                       2 non-null      float64
 71  applicant_race_observed                   50000 non-null  int64
 72  co-applicant_race_observed                50000 non-null  int64
 73  applicant_sex                             50000 non-null  int64
 74  co-applicant_sex                          50000 non-null  int64
 75  applicant_sex_observed                    50000 non-null  int64
 76  co-applicant_sex_observed                 50000 non-null  int64
 77  applicant_age                             50000 non-null  object
 78  co-applicant_age                          50000 non-null  object
 79  applicant_age_above_62                    45255 non-null  object
 80  co-applicant_age_above_62                 21240 non-null  object
 81  submission_of_application                 50000 non-null  int64
 82  initially_payable_to_institution          50000 non-null  int64
 83  aus-1                                     50000 non-null  int64
 84  aus-2                                     3357 non-null   float64
 85  aus-3                                     746 non-null    float64
 86  aus-4                                     210 non-null    float64
 87  aus-5                                     183 non-null    float64
 88  denial_reason-1                           50000 non-null  int64
 89  denial_reason-2                           731 non-null    float64
 90  denial_reason-3                           100 non-null    float64
 91  denial_reason-4                           14 non-null     float64
 92  tract_population                          50000 non-null  int64
 93  tract_minority_population_percent         50000 non-null  float64
 94  ffiec_msa_md_median_family_income         50000 non-null  int64
 95  tract_to_msa_income_percentage            50000 non-null  int64
 96  tract_owner_occupied_units                50000 non-null  int64
 97  tract_one_to_four_family_homes            50000 non-null  int64
 98  tract_median_age_of_housing_units         50000 non-null  int64
dtypes: float64(32), int64(40), object(27)
memory usage: 37.8+ MB